import os
import io
import base64
from google import genai
from google.genai import types
from PIL import Image
from dotenv import load_dotenv

load_dotenv()

# Initialize the Gemini client
try:
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
except Exception as e:
    print(f"Error initializing GenAI client: {e}")
    client = None

def get_monster_prompt(image_path: str) -> str:
    """Analyze the image using Gemini and generate a prompt for a monster."""
    if not client:
        raise ValueError("GenAI client is not initialized.")

    try:
        with open(image_path, "rb") as f:
            image_bytes = f.read()
            
        # We use gemini-2.5-flash
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[
                "Describe the main subject of this image in a few words, focusing on its physical characteristics. Then, write a prompt to generate a 2D pixel art sprite sheet of a cute monster inspired by this description. The sprite sheet must have a solid white background and feature the monster standing still in the first frame, and walking in the subsequent frames.",
                types.Part.from_bytes(
                    data=image_bytes,
                    mime_type='image/jpeg',
                )
            ]
        )
        base_desc = response.text.replace('\n', ' ')
        
        final_prompt = (
            f"A 2D pixel art sprite sheet of a cute monster. {base_desc}. "
            "The style must be 16-bit retro game pixel art. "
            "Layout: A single row of 4 equally sized frames. "
            "Frame 1: The monster standing still, facing forward. "
            "Frames 2, 3, 4: The monster walking forward in a walk cycle animation. "
            "The background must be solid pure white (#FFFFFF)."
        )
        print(f"Generated Image Prompt: {final_prompt}")
        return final_prompt
            
    except Exception as e:
        print(f"Error in Gemini analysis: {e}")
        return "A 2D pixel art sprite sheet of a cute generic slime monster, 16-bit retro style, solid white background. 4 frames in a single horizontal row showing a walk cycle."

def generate_sprite_sheet(prompt: str, output_path: str):
    """Generate the sprite sheet and save it."""
    if not client:
        raise ValueError("GenAI client is not initialized.")

    try:
        print(f"Calling Image Generation API with prompt: {prompt}")
        result = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="16:9",
                output_mime_type="image/jpeg",
                person_generation="ALLOW_ADULT"
            )
        )
        
        if not result.generated_images:
            raise ValueError("No image generated by the API.")

        generated_image = result.generated_images[0]
        img_bytes = generated_image.image.image_bytes
        
        if not img_bytes:
            raise ValueError("No image_bytes found in the generated image.")
            
        with open(output_path, "wb") as f:
            f.write(img_bytes)
            
        print(f"Successfully saved generated image to {output_path}")

    except Exception as e:
        print(f"Error in Image generation: {e}")
        raise e

if __name__ == "__main__":
    import sys
    
    # Use sample.jpg by default if no argument is provided
    input_image = sys.argv[1] if len(sys.argv) > 1 else "sample.jpg"
    output_image = "output_sprite.jpg"
    
    if not os.path.exists(input_image):
        print(f"Error: Input image '{input_image}' not found.")
        sys.exit(1)
        
    print(f"--- Starting local test with {input_image} ---")
    prompt = get_monster_prompt(input_image)
    generate_sprite_sheet(prompt, output_image)
    print("--- Done ---")
