import os
import io
import base64
from fastapi import FastAPI, File, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from fastapi.staticfiles import StaticFiles
from google import genai
from google.genai import types
from PIL import Image
from dotenv import load_dotenv

load_dotenv()

app = FastAPI()

# Enable CORS for the frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize the Gemini client
# Ensure GEMINI_API_KEY is in your .env file
try:
    client = genai.Client(api_key=os.getenv("GEMINI_API_KEY"))
except Exception as e:
    print(f"Error initializing GenAI client: {e}")
    client = None

def get_monster_prompt(image_bytes: bytes) -> str:
    """Analyze the image using Gemini and generate a prompt for a monster."""
    if not client:
        raise ValueError("GenAI client is not initialized.")

    try:
        # We use gemini-2.5-flash as it is fast and good for image understanding
        response = client.models.generate_content(
            model='gemini-2.5-flash',
            contents=[
                "Describe the main subject of this image in a few words, focusing on its physical characteristics. Then, write a prompt to generate a 2D pixel art sprite sheet of a cute monster inspired by this description. The sprite sheet must have a solid white background and feature the monster standing still in the first frame, and walking in the subsequent frames.",
                types.Part.from_bytes(
                    data=image_bytes,
                    mime_type='image/jpeg',
                )
            ]
        )
        # Extract just the prompt part if possible, or use the whole response.
        # For robustness, we will create a dedicated prompt structure.
        base_desc = response.text.replace('\n', ' ')
        
        final_prompt = (
            f"A 2D pixel art sprite sheet of a cute monster. {base_desc}. "
            "The style must be 16-bit retro game pixel art. "
            "Layout: A single row of 4 equally sized frames. "
            "Frame 1: The monster standing still, facing forward. "
            "Frames 2, 3, 4: The monster walking forward in a walk cycle animation. "
            "The background must be solid pure white (#FFFFFF)."
        )
        print(f"Generated Image Prompt: {final_prompt}")
        return final_prompt
            
    except Exception as e:
        print(f"Error in Gemini analysis: {e}")
        # Default fallback prompt
        return "A 2D pixel art sprite sheet of a cute generic slime monster, 16-bit retro style, solid white background. 4 frames in a single horizontal row showing a walk cycle."

def generate_sprite_sheet(prompt: str) -> str:
    """Generate the sprite sheet using Imagen 3 and return it as a base64 string."""
    if not client:
        raise ValueError("GenAI client is not initialized.")

    try:
        # Using Imagen 4 for high quality generation
        result = client.models.generate_images(
            model='imagen-4.0-generate-001',
            prompt=prompt,
            config=types.GenerateImagesConfig(
                number_of_images=1,
                aspect_ratio="16:9", # Wider to accommodate multiple frames in a row
                output_mime_type="image/jpeg",
                person_generation="ALLOW_ADULT"
            )
        )
        
        if not result.generated_images:
            raise ValueError("No image generated by the API.")

        generated_image = result.generated_images[0]
        # The generated_image object contains `image` which is a `types.Image` object
        img_bytes = generated_image.image.image_bytes
        
        if not img_bytes:
            raise ValueError("No image_bytes found in the generated image.")
            
        base64_encoded = base64.b64encode(img_bytes).decode('utf-8')
        
        return base64_encoded

    except Exception as e:
        print(f"Error in Image generation: {e}")
        raise e

@app.post("/generate")
async def generate_monster(file: UploadFile = File(...)):
    try:
        contents = await file.read()
        
        print("Analyzing image...")
        prompt = get_monster_prompt(contents)
        
        print("Generating sprite sheet...")
        sprite_base64 = generate_sprite_sheet(prompt)
        
        return JSONResponse(status_code=200, content={"sprite_base64": sprite_base64, "prompt_used": prompt})
    
    except Exception as e:
        return JSONResponse(status_code=500, content={"error": str(e)})

@app.get("/health")
def health_check():
    return {"status": "ok"}

# Mount the static files (frontend) at the root
frontend_dir = os.path.join(os.path.dirname(__file__), "..", "frontend")
root_dir = os.path.join(os.path.dirname(__file__), "..")

# Serve sample.jpg from the root dir
from fastapi.responses import FileResponse
@app.get("/sample.jpg")
async def get_sample():
    return FileResponse(os.path.join(root_dir, "sample.jpg"))

app.mount("/", StaticFiles(directory=frontend_dir, html=True), name="frontend")

